name: Sean Bedford 
description: Ramblings of a guy who does stuff with Microsoft tech
avatar: https://avatars1.githubusercontent.com/u/1159074
footer-links:
  dribbble: 
  email: sean.bedford@gmail.com
  facebook: 
  flickr: 
  github: https://github.com/sbedford
  instagram: 
  linkedin: au.linkedin.com/in/seanbedford
  pinterest: 
  rss: 
  twitter: sbedford
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
disqus: seanbedford
google_analytics: UA-59499981-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://sbedford.github.io

# If you're hosting your site at a Project repository on GitHub pages 
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: redcarpet
highlighter: pygments
permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.0.0

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - sbedford.github.io.sublime-project
    - sbedford.github.io.sublime-workspace
